    // vars/buildModulesWithJDK.groovy

    /**
    * Builds a module using specified JDK (SMG, compile, Nexus).
    * Security tools run linearly via {@code vars/securityToolsOrchestrator.groovy} (per-tool scripts {@code vars/tool*.groovy});
    * M2 / Node debug bash fragments and Groovy M2 context live in {@code vars/debug.groovy}; effective level from {@code JENKINS_PIPELINE_DEBUG} or {@code JENKINS_M2_DEBUG} via {@code vars/cxPipelineConfig.groovy};
    * Bash for {@code run_build.sh} is generated by {@code vars/mainBuildAndSonarScript.groovy};
    * GitLab namespace discovery: {@code vars/moduleSpecialCases.groovy}; SBOM paths: {@code vars/sbomDiscovery.groovy};
    * this script calls {@code securityToolsOrchestrator.runBranchSecurityTooling(...)} after generating {@code run_build.sh}.
    *
    * @param moduleName Name of the module.
    * @param jdkVersion Selected JDK (e.g., 'jdk-17').
    * @param workspacePath Directory for the build.
    * @param cxSmgBase Path to CX build tools.
    * @param isCoreType Boolean (True: No Nexus, False: Push to Nexus).
    * @param customBranchOverride The specific branch selected via the UI dropdown.
    * @param runSecurityTools When false, skip SonarQube, SBOM, Dependency-Track, DefectDojo, and JaCoCo (e.g. release pipeline). Default true. Combined with global JENKINS_RUN_SECURITY_TOOLS.
    * @param pipelineCfg Optional map from {@code cxPipelineConfig} — when set (or env {@code CX_PIPELINE_CFG_JSON} from Validate stage), skips redundant {@code cxPipelineConfig()} per parallel JDK cell (Option A).
    * Release-tag builds (tag push + {@code run_build_from_tag.sh}) live in {@code vars/buildModulesWithJDKReleaseTag.groovy} — not this script.
    */
    def call(String moduleName, String jdkVersion, String workspacePath, String cxSmgBase, boolean isCoreType, String customBranchOverride = null, Boolean runSecurityTools = true, Map pipelineCfg = null) {
        def runSecurityToolsParams = loadSharedLibVarScript('runSecurityToolsParams')
        if (!runSecurityToolsParams) {
            error '❌ runSecurityToolsParams could not be loaded from the shared library.'
        }
        boolean jobRunSecurityTools = runSecurityToolsParams.resolveJobRunSecurityTools(runSecurityTools)
        if (!moduleName) { error "❌ No module name provided." }
        def getDefaultsScript = loadSharedLibVarScript('getDefaults')
        boolean globalSecurityTools = getDefaultsScript != null && getDefaultsScript.getRunSecurityTools()
        boolean effectiveRunSecurityTools = globalSecurityTools && jobRunSecurityTools
        def secCat = loadSharedLibVarScript('securityToolsCatalog')
        boolean useCycloneDxSbom = secCat == null || secCat.isToolEffective('cyclonedx_sbom', effectiveRunSecurityTools)
        boolean useJacocoCatalog = secCat == null || secCat.isToolEffective('jacoco', effectiveRunSecurityTools)
        boolean useSonar = secCat == null || secCat.isToolEffective('sonarqube', effectiveRunSecurityTools)

        def serde = loadSharedLibVarScript('pipelineConfigSerde')
        def cfg
        if (pipelineCfg != null) {
            cfg = new LinkedHashMap(pipelineCfg as Map)
            echo 'ℹ️ Using injected pipelineCfg (cxPipelineConfig skipped for this module/JDK cell).'
        } else if (env.CX_PIPELINE_CFG_JSON?.toString()?.trim() && serde != null) {
            cfg = serde.pipelineConfigFromJson(env.CX_PIPELINE_CFG_JSON.toString())
            if (cfg != null) {
                echo 'ℹ️ Using CX_PIPELINE_CFG_JSON from Validate stage (cxPipelineConfig skipped for this module/JDK cell).'
            }
        }
        if (cfg == null) {
            cfg = cxPipelineConfig(effectiveRunSecurityTools)
        }
        def reactCiResolver = loadSharedLibVarScript('resolveReactCiEnv')
        String reactCiExport = cfg.reactCiExport?.toString()?.trim()
        if (!(reactCiExport in ['true', 'false']) && reactCiResolver) {
            reactCiExport = reactCiResolver.effective(cfg)
        }
        if (!(reactCiExport in ['true', 'false'])) {
            reactCiExport = 'false'
        }
        boolean pipelineVerbose = cfg.m2DebugExplicit == 'true'
        if (pipelineVerbose) {
            echo "⚙️ Initializing Build for: ${moduleName} (JDK: ${jdkVersion}, Core: ${isCoreType}, Security tools: ${effectiveRunSecurityTools} [global=${globalSecurityTools}, param=${jobRunSecurityTools}])"
        } else {
            echo "⚙️ Build ${moduleName} (${jdkVersion})${isCoreType ? ' core' : ''}"
        }
        def toolSbomJacoco = loadSharedLibVarScript('toolSbomJacoco')
        def toolSonarqube = loadSharedLibVarScript('toolSonarqube')
        def securityToolsCommon = loadSharedLibVarScript('securityToolsCommon')
        def securityOrchestrator = loadSharedLibVarScript('securityToolsOrchestrator')
        if (!toolSbomJacoco || !toolSonarqube || !securityToolsCommon || !securityOrchestrator) {
            error '❌ toolSbomJacoco, toolSonarqube, securityToolsCommon, or securityToolsOrchestrator could not be loaded from the shared library.'
        }
        def gitHost = cfg.gitHost
        def resolveCxSmgDevPathScript = loadSharedLibVarScript('resolveCxSmgDevPath')
        def dbg = loadSharedLibVarScript('debug')
        if (!dbg) { error "❌ debug helper not found in shared library." }
        def mainBuildSonarRenderer = loadSharedLibVarScript('mainBuildAndSonarScript')
        if (!mainBuildSonarRenderer) { error "❌ mainBuildAndSonarScript not found in shared library." }
        def nexusUrls = loadSharedLibVarScript('nexusUploadUrls')
        if (!nexusUrls) { error "❌ nexusUploadUrls not found in shared library." }
        def moduleSpecialCases = loadSharedLibVarScript('moduleSpecialCases')
        if (!moduleSpecialCases) { error "❌ moduleSpecialCases not found in shared library." }
        def sbomDiscovery = loadSharedLibVarScript('sbomDiscovery')
        if (!sbomDiscovery) { error "❌ sbomDiscovery not found in shared library." }
        def cxSmgDevResolved = resolveCxSmgDevPathScript.call(cxSmgBase)
        dbg.pipelineLog(pipelineVerbose, "📌 SMG CX_SMG_DEV resolved to: ${cxSmgDevResolved} (raw CX_SMG_DEV='${env.CX_SMG_DEV}')")

        withCredentials([
            usernamePassword(credentialsId: cfg.gitHttpCredentialId, usernameVariable: 'G_USR', passwordVariable: 'G_PWD'),
            usernamePassword(credentialsId: cfg.nexusCredentialId, usernameVariable: 'N_USR', passwordVariable: 'N_PWD')
        ]) {
            def netrcScript = """echo "machine ${gitHost} login ${G_USR} password ${G_PWD}" > ~/.netrc && chmod 600 ~/.netrc"""
            sh netrcScript

            try {
                dir(workspacePath) { // Enter the module's specific workspace
                    deleteDir()

                    // PIPELINE_DEBUG (matches JENKINS_PIPELINE_DEBUG / JENKINS_M2_DEBUG) for git steps + bash fragments in run_build.sh
                    withEnv(["PIPELINE_DEBUG=${cfg.m2DebugExplicit}"]) {

                    // 1. BRANCH — must come from job parameters / caller (vars/cxPipelineConfig documents CX_* env; no legacy defaults here)
                    if (!customBranchOverride?.toString()?.trim() || customBranchOverride.toString().trim() == 'null') {
                        error "❌ customBranchOverride (Git branch or tag) is required. Configure branch per module in the job parameters."
                    }
                    def moduleBranch = customBranchOverride.toString().trim()
                    dbg.pipelineLog(pipelineVerbose, "🔗 Branch Strategy: ${moduleBranch}")

                    // 2. FETCH SONAR COMMAND (only when security tools enabled)
                    def sonarCmd = useSonar ? getSonarCommand(moduleName, moduleBranch) : ""

                    // 3. NAMESPACE DISCOVERY (special cases: vars/moduleSpecialCases.groovy)
                    def gitOrgForDiscover = cfg.gitOrg?.toString()?.trim() ?: env.CX_GIT_ORG?.toString()?.trim()
                    if (!gitOrgForDiscover) {
                        error '❌ Git org is not configured. Set JENKINS_GIT_ORG or CX_GIT_ORG (Jenkins global or job environment).'
                    }
                    def namespaceScript = moduleSpecialCases.buildDiscoverNamespaceScript(gitHost, gitOrgForDiscover, moduleName)
                    writeFile file: "discover.sh", text: namespaceScript
                    def namespace = sh(script: "bash discover.sh", returnStdout: true).trim()

                    // 4. GIT INIT & FETCH (handles both branches and tags)
                    def cloneUrl = "https://${gitHost}/${gitOrgForDiscover}/${namespace}/${moduleName}.git"
                    sh """
                        git init
                        git remote add origin ${cloneUrl}
                        # Fetch the ref (works for both branches and tags)
                        # Try as branch first, then as tag if branch fetch fails
                        if git fetch origin refs/heads/${moduleBranch}:refs/remotes/origin/${moduleBranch} 2>/dev/null; then
                            if [ "\${PIPELINE_DEBUG}" = "true" ]; then echo "✅ Fetched as branch: ${moduleBranch}"; fi
                            git checkout -f refs/remotes/origin/${moduleBranch}
                        elif git fetch origin refs/tags/${moduleBranch}:refs/tags/${moduleBranch} 2>/dev/null; then
                            if [ "\${PIPELINE_DEBUG}" = "true" ]; then echo "✅ Fetched as tag: ${moduleBranch}"; fi
                            git checkout -f refs/tags/${moduleBranch}
                        else
                            # Fallback: try generic fetch (works for both branches and tags)
                            git fetch origin ${moduleBranch}
                            git checkout -f FETCH_HEAD
                        fi
                    """

                    // 5. PREPARE ENVIRONMENT & BUILD SCRIPT
                    def cleanJdk = jdkVersion.replace('jdk-', '')
                    def buildTypeSuffix = cfg.buildTypeSuffix
                    // Nexus path uses short version: jdk17-4.10-SNAPSHOT (not jdk17-develop-4.10.x-SNAPSHOT)
                    def nexusShortVersion = securityToolsCommon.getNexusShortVersion(moduleBranch)
                    def nexusPathDir = "jdk${cleanJdk}-${nexusShortVersion}-${buildTypeSuffix}"

                    dbg.echoM2PipelineContext(moduleName, jdkVersion, buildTypeSuffix, null, cfg.m2DebugExplicit == 'true')

                    // SBOM_FILE path (vars/sbomDiscovery.groovy)
                    def relativeSbomPath = sbomDiscovery.getRelativeSbomPath(moduleName)

                    def cxGitOrgSeg = env.CX_GIT_ORG?.toString()?.trim() ?: cfg.gitOrg?.toString()?.trim()
                    if (!cxGitOrgSeg) {
                        error '❌ Git org is not configured. Set JENKINS_GIT_ORG or CX_GIT_ORG (Jenkins global or job environment).'
                    }
                    def cxGitOrgSmg = env.CX_GIT_ORG?.toString()?.trim() ?: cxGitOrgSeg
                    def ccInstallerBranchSuffix = env.BUILD_NUMBER?.toString()?.trim() ?: '0'
                    def bashCommand = (env.JENKINS_CD_BASH_X?.toString() == 'true') ? 'bash -x' : 'bash'
                    def javaSetupBlock = """
                            if [ -n "\${JAVA_HOME:-}" ] && [ -x "\${JAVA_HOME}/bin/java" ]; then
                                export PATH="\${JAVA_HOME}/bin:\${PATH}"
                            elif [ -n "\$JDK_${cleanJdk}_HOME" ] && [ -x "\$JDK_${cleanJdk}_HOME/bin/java" ]; then
                                export JAVA_HOME="\$JDK_${cleanJdk}_HOME"
                                export PATH="\${JAVA_HOME}/bin:\${PATH}"
                            elif command -v java >/dev/null 2>&1; then
                                _J="\$(command -v java)"
                                _R="\$(readlink -f "\$_J" 2>/dev/null || readlink "\$_J" 2>/dev/null || echo "\$_J")"
                                export JAVA_HOME="\$(dirname "\$(dirname "\$_R")")"
                                export PATH="\${JAVA_HOME}/bin:\${PATH}"
                            fi
                            export JDK_${cleanJdk}_HOME="\${JAVA_HOME}"
                            if [ "\${PIPELINE_DEBUG:-false}" = "true" ]; then echo "Build environment: JAVA_HOME=\${JAVA_HOME:-}"; fi
"""
                    // Jenkins sets JAVA_HOME from the selected JDK tool (withEnv). Sourcing ~/.bashrc first
                    // often overwrites it with the agent default (e.g. JDK 17), so we restore the pipeline JDK.
                    def preserveJdkBeforeBashrc = """
                            _CX_PIPELINE_JAVA_HOME="\${JAVA_HOME:-}"
                            . "\${HOME}/.bashrc" || true
                            if [ -n "\${_CX_PIPELINE_JAVA_HOME}" ] && [ -x "\${_CX_PIPELINE_JAVA_HOME}/bin/java" ]; then
                                export JAVA_HOME="\${_CX_PIPELINE_JAVA_HOME}"
                            fi
"""
                    // creinstaller.sh is only for CC; other installer modules use SMG pack-module.sh
                    def packInstallerCmd = '''bash "${CX_SMG_BASE}/bin/pack-module.sh"'''
                    def nexusBaseUrl = cfg.nexusBaseUrl

                    withEnv([
                        "SMG_MODULE=${moduleName}",
                        "SMG_BRANCH_NAME=${moduleBranch}",
                        "TARGET_NAMESPACE=${namespace}",
                        "SBOM_FILE=${relativeSbomPath}",
                        "BUILD_TYPE_SUFFIX=${buildTypeSuffix}",
                        "M2_DEBUG=${cfg.m2DebugExplicit}",
                        "PIPELINE_DEBUG=${cfg.m2DebugExplicit}",
                        "NEXUS_PATH_DIR=${nexusPathDir}",
                        "CLEAN_JDK=${cleanJdk}"
                    ]) {
                        def compilationBlock = toolSbomJacoco.getCompilationBlock(useCycloneDxSbom, useJacocoCatalog, moduleName)
                        def sonarBlock = toolSonarqube.getSonarBlock(useSonar, sonarCmd)
                        def mainBuildAndSonarScript = mainBuildSonarRenderer.render([
                            preserveJdkBeforeBashrc      : preserveJdkBeforeBashrc,
                            cxSmgBase                    : cxSmgBase,
                            cxSmgDevResolved             : cxSmgDevResolved,
                            javaSetupBlock               : javaSetupBlock,
                            cxGitOrg                     : cxGitOrgSmg,
                            cxGitOrgSeg                  : cxGitOrgSeg,
                            dbg                          : dbg,
                            compilationBlock             : compilationBlock,
                            sonarBlock                   : sonarBlock,
                            isCoreType                   : isCoreType,
                            moduleName                   : moduleName,
                            moduleBranch                 : moduleBranch,
                            namespace                    : namespace,
                            nexusBaseUrl                 : nexusBaseUrl,
                            nexusPathDir                 : nexusPathDir,
                            nexusUploadPrefix            : nexusUrls.nexusPackageImagesUploadUrlPrefix(nexusBaseUrl, moduleName, nexusPathDir),
                            ccInstallerBranchSuffix      : ccInstallerBranchSuffix,
                            packInstallerCmd             : packInstallerCmd,
                            nexusUser                    : N_USR,
                            nexusPassword                : N_PWD,
                            reactCiExport                : reactCiExport
                        ])
                        writeFile file: "run_build.sh", text: mainBuildAndSonarScript

                        securityOrchestrator.runBranchSecurityTooling(
                            bashCommand              : bashCommand,
                            effectiveRunSecurityTools: effectiveRunSecurityTools,
                            cfg                      : cfg,
                            moduleName               : moduleName,
                            moduleBranch             : moduleBranch,
                            jdkVersion               : jdkVersion,
                            namespace                : namespace,
                            qgTimeoutMinutes         : 30
                        )

                        def nexusLogUrl
                        if (isCoreType) {
                            nexusLogUrl = "${(nexusBaseUrl ?: '').toString().trim().replaceAll(/\/+$/, '')}/"
                        } else {
                            boolean ccCre = nexusUrls.nexusCxCreinstallerModule(moduleName, env.CX_CREINSTALLER_MODULES?.toString())
                            def instBase = nexusUrls.nexusPackageImagesInstallerBasename(moduleName, cleanJdk, nexusPathDir, ccCre)
                            nexusLogUrl = nexusUrls.nexusPackageImagesInstallerFileUrl(nexusBaseUrl, moduleName, nexusPathDir, instBase)
                        }
                        echo "${moduleName}: ${nexusLogUrl}"
                    }
                    } // withEnv PIPELINE_DEBUG
                } // End of dir(workspacePath) block
            } finally {
                sh "rm -f ~/.netrc"
            }
        }
    }
