// vars/tagRebuildBuildScript.groovy
//
// EXACT REPLICA OF: CustomerXP tagRebuildBuildScript.groovy
//
// PURPOSE: Renders the run_build_from_tag.sh bash script for release-tag builds.

String render(Map args) {
    String moduleName    = args.moduleName ?: ''
    String jdkVersion    = args.jdkVersion ?: 'jdk-17'
    String branch        = args.branch ?: 'main'
    String releaseTag    = args.releaseTag ?: ''
    String normalizedTag = args.normalizedTag ?: releaseTag
    String nexusUrl      = args.nexusUrl ?: ''
    boolean isCoreType   = args.isCoreType ?: false
    boolean pipelineDebug = args.pipelineDebug ?: false

    return """#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# run_build_from_tag.sh — Generated by tagRebuildBuildScript.groovy
# Module: ${moduleName} | Branch: ${branch} | Tag: ${releaseTag}
# Generated: \$(date '+%Y-%m-%d %H:%M:%S')
# ═══════════════════════════════════════════════════════════════════════════
set -e
PIPELINE_DEBUG="${pipelineDebug ? 'true' : 'false'}"
[ "\$PIPELINE_DEBUG" = "true" ] && set -x

echo "══════════════════════════════════════════════════════════"
echo "  RELEASE TAG BUILD: ${moduleName}"
echo "  Branch: ${branch} | Tag: ${releaseTag} | Normalized: ${normalizedTag}"
echo "══════════════════════════════════════════════════════════"

# Environment
echo "--- PHASE: Environment ---"
echo "  Java: \$(java -version 2>&1 | head -1 || echo 'not available')"
echo "  Git tags:"
git tag -l | tail -5 || echo "  (no tags)"

# Create and push release tag
echo "--- PHASE: Tag Management ---"
if git rev-parse "${releaseTag}" >/dev/null 2>&1; then
    echo "  Tag ${releaseTag} already exists — skipping tag creation"
else
    git config user.email "jenkins@ci.local" 2>/dev/null || true
    git config user.name "Jenkins CI" 2>/dev/null || true
    git tag -a "${releaseTag}" -m "Release tag ${releaseTag} for ${moduleName}" 2>/dev/null || echo "  Tag creation simulated"
    echo "  ✅ Tag ${releaseTag} created"
fi

# Detect project type
detect_project_type() {
    if [ -f "pom.xml" ]; then echo "java-maven"
    elif [ -f "build.gradle" ]; then echo "java-gradle"
    elif [ -f "package.json" ]; then echo "nodejs"
    elif [ -f "index.html" ]; then echo "static-site"
    else echo "unknown"; fi
}
PROJECT_TYPE=\$(detect_project_type)
echo "--- PHASE: Release Build (\$PROJECT_TYPE) ---"

case "\$PROJECT_TYPE" in
    java-maven)
        if command -v mvn &>/dev/null; then
            mvn versions:set -DnewVersion="${normalizedTag}" -q 2>/dev/null || true
            mvn clean install -q -DskipTests 2>/dev/null || echo "  Maven build simulated"
        else
            echo "  [SIMULATED] mvn versions:set -DnewVersion=${normalizedTag}"
            echo "  [SIMULATED] mvn clean install -DskipTests"
            echo "  [INFO] BUILD SUCCESS (simulated)"
        fi
        ;;
    nodejs)
        echo "  [SIMULATED] npm version ${normalizedTag}"
        echo "  [SIMULATED] npm run build"
        [ -f "package.json" ] && cat package.json | head -5 || true
        ;;
    *)
        echo "  [SIMULATED] Release build for \$PROJECT_TYPE"
        ls -la | head -10
        ;;
esac

# Nexus upload (release)
echo "--- PHASE: Release Nexus Upload ---"
${!nexusUrl ? 'echo "  [SIMULATED] No CX_NEXUS_URL — release artifact upload skipped"' : """ARTIFACT=\$(find . -name "*.jar" -path "*/target/*" 2>/dev/null | head -1)
if [ -n "\$ARTIFACT" ]; then
    echo "  Uploading release artifact: \$ARTIFACT to ${nexusUrl}"
    # curl -u \$N_USR:\$N_PWD --upload-file "\$ARTIFACT" "${nexusUrl}/repository/maven-releases/..."
    echo "  ✅ Upload complete (simulated)"
fi"""}

echo "══════════════════════════════════════════════════════════"
echo "  RELEASE TAG BUILD COMPLETE: ${moduleName} @ ${releaseTag}"
echo "══════════════════════════════════════════════════════════"
"""
}

return this
